[project]
name = "py-ws-signal-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dataclasses-json>=0.6.7",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
